--CREATE TABLE Students(id INTEGER PRIMARY KEY AUTOINCREMENT,
--                      firstname TEXT NOT NULL,
--                      lastname TEXT NOT NULL,
--                      dob TEXT NOT NULL);
--CREATE TABLE Marks(id INTEGER PRIMARY KEY AUTOINCREMENT,
--                      student_id INTEGER,
--                      subject TEXT NOT NULL,
--                      mark INTEGER);

--INSERT INTO Marks(student_id, subject, mark)
--              VALUES(1,'English',50),
--                    (1,'Maths',100),
--                    (2,'English',67),
--                    (2,'Science',80),
--                    (3,'English',24),
--                    (4,'English',97),
--                    (5,'Maths',82),
--                    (5,'Science',5);

--SELECT lastname, dob FROM Students;
--SELECT firstname, lastname FROM Students
--    ORDER BY lastname;
--SELECT firstname, lastname, dob FROM Students
--    WHERE dob LIKE '%%%%%%2007';
--SELECT * FROM Marks;
--SELECT * FROM Marks
--    WHERE subject LIKE 'English';
--SELECT subject, mark FROM Marks
--    WHERE mark < 50;
--SELECT subject, mark FROM Marks
--    WHERE mark > 49;